eureka:
  instance:
    hostname: ${EUREKA_HOST_NAME}
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
server:
  port: ${SERVER_PORT}
spring:
  application:
    name: schools
  config:
    import: optional:configserver:${SPRING_CONFIG_SERVER}
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
application:
  config:
    students-url: ${STUDENT_CLIENT_URL}