server:
  port: 8888
spring:
  profiles:
    active: dev
  application:
    name: configserver
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
